CREATE TABLE accident (
    casenum VARCHAR(20) NOT NULL,
    urbancityname VARCHAR(10) NOT NULL,
    ve_total INTEGER NOT NULL,
    permvit INTEGER NOT NULL,
    num_inj INTEGER NOT NULL,
    "month" SMALLINT NOT NULL,
    "year" SMALLINT NOT NULL,
    wrk_zonename SMALLINT NOT NULL,
    wkdy_imname VARCHAR(10) NOT NULL,
    hour_im SMALLINT NOT NULL,
    lgtcon_imname VARCHAR(25) NOT NULL,
    weathr_imname VARCHAR(25) NOT NULL,
    maxsev_imname VARCHAR(30) NOT NULL,
    no_inj_im SMALLINT NOT NULL,
    alchl_imname VARCHAR(20) NOT NULL,
    PRIMARY KEY (casenum)
);

CREATE TABLE vehicle (
    casenum VARCHAR(20) NOT NULL,
    veh_no SMALLINT NOT NULL,
    numoccs SMALLINT NOT NULL,
    m_harmname VARCHAR(150) NOT NULL,
    makename VARCHAR(40) NOT NULL,
    tow_vehname VARCHAR(40) NOT NULL,
    trav_speed SMALLINT NOT NULL,
    deformedname VARCHAR(20) NOT NULL,
    towedname VARCHAR(40) NOT NULL,
    speedrelname VARCHAR(50) NOT NULL,
    vtrafwayname VARCHAR(60) NOT NULL,
    vspd_lim SMALLINT NOT NULL,
    bdytyp_imname VARCHAR(100) NOT NULL,
    mdlyr_im SMALLINT NOT NULL,
    pcrash1_imname VARCHAR(50) NOT NULL,
    PRIMARY KEY (casenum, veh_no),
    FOREIGN KEY (casenum) REFERENCES accident(casenum)
);

CREATE TABLE person (
    casenum VARCHAR(20) NOT NULL,
    ve_forms SMALLINT NOT NULL,
    veh_no SMALLINT NOT NULL,
    per_no SMALLINT NOT NULL,
    rest_usename VARCHAR(50) NOT NULL,
    helm_usename VARCHAR(50) NOT NULL,
    helm_misname VARCHAR(50) NOT NULL,
    rest_misname VARCHAR(50) NOT NULL,
    drinkingname VARCHAR(25) NOT NULL,
    alc_resname VARCHAR(50) NOT NULL,
    drugsname VARCHAR(25) NOT NULL,
    hospitalname VARCHAR(50) NOT NULL,
    locationname VARCHAR(100) NOT NULL,
    sex_imname VARCHAR(10) NOT NULL,
    injsev_imname VARCHAR(50) NOT NULL,
    peralch_imname VARCHAR(25) NOT NULL,
    seat_imname VARCHAR(100) NOT NULL,
    age_im SMALLINT NOT NULL,
    PRIMARY KEY (casenum, veh_no, per_no),
    FOREIGN KEY (casenum, veh_no) REFERENCES vehicle(casenum, veh_no)
);